### ISSUE TITLE
Date text field no longer being localized

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#154]
Although date parsing from a text field with SugarJS has been restored in the current version of the add-on, the date text being inserted into the text field is no longer being localized as it was in TB78. This was reported to us in https://addons.thunderbird.net/en-US/thunderbird/addon/send-later-3/reviews/1164759/.

**Comment by DenB10** [comment]
@jikamens 
Hello Jonathan,
I'm the author of the review you mentioned. Thank you for reporting this here.
I hope Jonathan Perry-Houts will address this issue soon.

**Comment by jperryhouts** [comment]
@DenB10 Can you explain which places in particular are not being localized? I ask because send later uses several different functions for formatting dates and times depending on the context.

**Comment by DenB10** [comment]
The problem appeared when you replaced moment with sugar. So I think that comes from sugar.
But a picture is better than a long speech:

![screen1](https://user-images.githubusercontent.com/9309147/100482626-5ae65800-30f8-11eb-8fb8-b3587a5d5ff8.png)

**Comment by jperryhouts** [comment]
Got it, thanks. Looks like Sugar is much better at parsing dates, but less intelligent about formatting them for whatever reason. This should be fixed by #164

**Comment by DenB10** [comment]
Thank you for the extremely fast fix. It works but the problem is not entirely solved. There is still the "from now" that is present in sugar but not called in send later. See screenshot:

![Presse-papiers-1](https://user-images.githubusercontent.com/9309147/100485702-65591f80-3101-11eb-8a00-fce2302902fc.png)

**Comment by jperryhouts** [comment]
Very weird. I assumed that Sugar would automatically choose the right locale settings. What happens if you open the console window (ctrl+shift+J) and copy-paste this line into it:

> var locale = window.ExtensionParent.GlobalManager.extensionMap.get("sendlater3@kamens.us").localeData; console.log(`Sugar: ${Sugar.Date.getLocale().code}\ndefault: ${locale.defaultLocale}\nSelected: ${locale.selectedLocale}`);

**Comment by DenB10** [comment]
Return:

Sugar: en
default: en
Selected: fr

**Comment by jperryhouts** [comment]
Huh. ok, I guess I need to explicitly tell sugarjs to use the selected language, not the default. Just to check that this will get the right value, what does the following line output?

    var ex = window.ExtensionParent.GlobalManager.extensionMap.get("sendlater3@kamens.us"); console.log("i18n language:",[...ex.views][0].apiCan.findAPIPath("i18n").getUILanguage());

**Comment by DenB10** [comment]
i18n language: fr

**Comment by jperryhouts** [comment]
:+1:  Thank you for your help with that. This should be fixed by #166

**Comment by DenB10** [comment]
Ok in the popup but not in the draft folder: the "Send Later" is empty and the header button returns:

ERROR
date value is not finite in DateTimeFormat.format()

**Comment by DenB10** [comment]
... And of course, the message is not sent!

**Comment by jperryhouts** [comment]
Ah, sorry about that. I forgot that the locale settings are not available to some parts of the code right away. That should be fixed by #168 

But if the messages are not sending that might be another issue. The problem preventing dates from showing up in the column should have only affected the user interface. Let me know if this last patch doesn't fix it.

**Comment by DenB10** [comment]
No, same result as before:

![Presse-papiers-1](https://user-images.githubusercontent.com/9309147/100499105-3aa1b200-3167-11eb-942b-a1f39f454914.png)

Sorry!

**Comment by jperryhouts** [comment]
Man. Localization is not working well for you at all -- Is the send later column always in English for you?

Can you check the message source for this message (ctrl+U I believe). Is there something weird about the "x-send-later-at" header? Does this happen for new messages as well?

**Comment by jperryhouts** [comment]
I switched my locale to french to do more testing and I figured out why the column title is not being translated (fixed in #171) but that still doesn't explain the error.

**Comment by DenB10** [comment]
Yes, the send later column is always in English.

There are 3 "X-Send-Later" headers:
X-Send-Later-Uuid
X-Send-Later-At (with the right scheduled date in French)
X-Send-Later-Recur

So, everything seems OK. Nothing different in the headers with the previous version 8.4.5 (except the date is in English). I don't understand!

**Comment by DenB10** [comment]
> 
> 
> I switched my locale to french to do more testing and I figured out why the column title is not being translated (fixed in #171) but that still doesn't explain the error.

The column is effectively in French now but always empty and the same error occurs. Do you have this error when you switch your locale to fr?

**Comment by jperryhouts** [comment]
It all looks okay for me

![Screenshot from 2020-11-28 10-22-56](https://user-images.githubusercontent.com/6118266/100523245-db8e6e00-3163-11eb-8a15-de2e4e9157ac.png)

But I did find some more places where date conversion and parsing could be made more robust (#172). Could you post the actual value of the x-send-later-at header? The formatting on those can be a bit more particular than most date strings.

Also, just to confirm this also happens if you schedule a new message, not just on messages that are already there?

**Comment by DenB10** [comment]
Headers for a new scheduled message (with last fix):
X-Send-Later-Uuid: {fb078194-e424-4a27-98d8-3d550fd6c8e8}
X-Send-Later-At: sam, 28 nov 2020 20:09:40 +0100
X-Send-Later-Recur: none

No error for the messages already scheduled with the previous version (8.4.5)

**Comment by DenB10** [comment]
Maybe, the error comes from the translated date for the "X-Send-Later-At" header!
The "Date" header is in English, as it must be.

**Comment by jperryhouts** [comment]
That sounds likely (but surprising!) -- if that's the case it should be fixed by #173

**Comment by DenB10** [comment]
Bingo! After several tries, I can say that this fix-up (#175) is the right one. Thank you very much! You have found it.

**Comment by jperryhouts** [comment]
Great. Thank you for helping work through that!
