### ISSUE TITLE
Date Picker always picks the wrong date

### ISSUE THREAD

**Issue by rewrib** [Extended-Thunder/send-later#631]
Today is the 6th of September in Germany.

The date picker, that lets you choose the date and time of when your email is being sent, seems to confused about whether "6th of September" means 06/09/2023 or 09/06/2023.

Image 1 shows what I see when I open the Send Later popup
![grafik](https://github.com/Extended-Thunder/send-later/assets/54379054/1b21eeb7-84b1-47d1-863f-a16fec7d9453)

Image 2 shows what I see when I enter a custom time into the text editor next to the date picker. I can't send the email anymore, because Send Later "forgets" that 06/09/2023 means 6th of Sep,
![grafik](https://github.com/Extended-Thunder/send-later/assets/54379054/8631a1be-afc3-431a-a783-89087fb763b3)

Afterwards when I close the Send Later popup and reopen the popup for the same message, the date picker changes from 06/09 to 09/06. I still can't send the message.
![grafik](https://github.com/Extended-Thunder/send-later/assets/54379054/673566b7-1656-4802-a553-c2af554e6a62)

When I adjust the time manually in the "Send at" text box, it does register the date normally though, as long as you consistently use the month/day/year format.

These are my time settings (Win10)
![grafik](https://github.com/Extended-Thunder/send-later/assets/54379054/4b2d3174-8c94-433e-8ca7-82ddda674e1e)

I use Send Later 10.1.6 together with Thunderbird 115.2.0.

**Comment by jikamens** [comment]
It looks like you're using an old version of Send Later. This should be fixed in the current version. Please make sure you've got version 10.1.6.

**Comment by rewrib** [comment]
Yes I have 10.1.6. I even removed the addon and reinstalled it from the Thunderbird add-ons store, but I still experience the same behavior in my setup.

![grafik](https://github.com/Extended-Thunder/send-later/assets/54379054/65468c88-235b-4b57-8df2-542576d9647b)

**Comment by jikamens** [comment]
Please disable and re-enable the add-on and then open the error console (Ctrl-Shift-J) and search for "locale" (enter "locale" in the filter box at the top) to find the line that Thunderbird logs at startup, which should show your UI locale and the locale the OS is using for date-parsing. Paste that here.

I suspect an incompatibility between the "English (Germany)" region you have configured and Send Later's date-parsing library. I'm just guessing here, but my suspicion is that the date-parsing library doesn't understand the "English (Germany)" region so it is falling back to American English parsing which uses m/d/y instead of d/m/y. I need to see your locale line to confirm.

I may be able to figure out how to fix it if you provide the above information, but you can also just fix it yourself by customizing your short date format [as documented in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up).

**Comment by AzizatEcom** [comment]
I just noticed that the new version of send later won't allow me to schedule emails until I set the send date to after 4 days. I also noticed that when I choose the 5th day it will schedule it for after 33 days means 4 days after the current date and 30 days for the 5th day, similarly it will add a month for any additional day.

For example current date is September 6. 
The earliest date it is allowing me to schedule the email is September 9
If I select September 10 - it will show me the sending date October 9
If I select September 11 - it will show me the sending date November 9 and so on.

**Comment by rewrib** [comment]
This what I got from the console:

Send Later version 10.1.6 on Thunderbird 115.2.0 (20230828145448) [win x86-64] UI locale en-US, Date Locale en-DE

**Comment by jikamens** [comment]
**Please test!**

This issue should be fixed in release 10.1.8 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.8) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.1.8/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.8 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know which this release fixes the issue for you.

**Comment by jikamens** [comment]
P.S. If you configured custom date formats earlier to work around this issue, you should remove them in the Send Later preferences when testing this new release or you aren't really testing it. ;-)

**Comment by tonkolviktor** [comment]
thanks @jikamens 

![image](https://github.com/Extended-Thunder/send-later/assets/4534324/77c2b6ac-e60a-4603-95c1-8fb24ff76da9)

I can confirm that 10.1.6 is incorrect, but a manually installed 10.1.8 fixes the issue.

**Comment by jikamens** [comment]
Fix released in 10.1.9.
