### ISSUE TITLE
Draft version is still in Gmail's own draft folder after sending the scheduled email with the add-on

### ISSUE THREAD

**Issue by henrikgit** [Extended-Thunder/send-later#641]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Send-later works pretty great. All is well in the land of sending mails later. :)

Then the draft gets deleted from Thunderbird's draft folder in the sub-folder of the relevant gmail-account. However when I go into my gmail account (whether it is through the app or the web version does not matter), the drafted email is still there.

### How to reproduce

1. Follow [the guide](https://extended-thunder.github.io/send-later/#basic-usage) to send/schedule an email to be sent later
2. Log into https://mail.google.com
3. Go to the *Drafts* folder, you'll see the draft from the already sent email there.

### Expected behavior

I expect/wish that there is not draft version left in the folder in gmail after the (scheduled) email was sent.

### Thunderbird version

115.2.0

### Send Later start-up string

`Später senden version 10.1.9 on Thunderbird 115.2.0 (20230911102327) [linux x86-64] UI locale de, Date Locale de-DE [tools.js:59:13](moz-extension://0aa2437f-5cb4-40d6-aee1-775653500c46/utils/tools.js)`

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.7 of Send Later if you set the `compactDrafts` advanced preference to `true`. See the details in the [beta user guide](https://extended-thunder.github.io/send-later/next/#advanced-configuration-editor).

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.7) as follows:

* Download [send_later.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.7/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

To subscribe to future beta releases (we love beta testers!), download and install [send_later_beta.xpi](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.7/send_later_beta.xpi) instead. The advantage is that if there's a bug that affects your workflow you'll help find it and get it fixed quickly. The disadvantage is that bugs are a bit more likely in beta releases. You can unsubscribe from beta releases at any time by downloading and installing send_later.xpi or installing from [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/).

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.7 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by henrikgit** [comment]
Hi Jonathan, thank you very much for your work on this issue. 

Did 2 tests with the downloaded `.xpi`-file. Unfortunately, I still see the 2 drafts on/in https://mail.google.com/mail/u/0/#drafts.

**Comment by jikamens** [comment]
@henrikgit Did you set the `composeDrafts` advanced preference to true as mentioned above?

**Comment by jikamens** [comment]
@henrikgit (Typo in comment above corrected, I initially typed `composeDrafts` when I meant `compactDrafts`.)

**Comment by henrikgit** [comment]
Oh. No. Sorry.

Now that I have, it works, the drafts are gone from https://mail.google.com/mail/u/0/#drafts :)

--> SOLVED :)
